#!/bin/sh

# Path to the tree file generated by BEAST
tree_file=$1
# Path to the coordinates file create by zoophy
coords_file=$2
# Job ID created by zoophy. A directory will be created
# with this name and will be used for generating frames
# and creating the video file
work_dir=$3

# Generate the frames for the spread
python -u pgmt.py -t $tree_file -l $coords_file -o output/$work_dir > output/$work_dir.log 2>&1

# Stitch the frames into a video
fps=15
output_dir=output/$work_dir
frames_dir="$output_dir/frames"
output_file="$output_dir/spread.mp4"
scale="2160:trunc(ow/a/2)*2"

ffmpeg -y -framerate $fps -start_number 0 -i $frames_dir/ani_frame_%05d.png -pix_fmt yuv420p -b:a 64k -vf scale=$scale $output_file
